In [68]:
import numpy as np

#  1

In [69]:
a = np.array ([[1,2,3],[4,5,6],[7,8,9]])
b = np.array ([[1,2,3],[4,5,6],[7,8,9]])
addition = np.add(a,b)
subtraction = np.subtract(a,b)
multiplication = np.multiply(a,b)
division = np.divide(a,b)

print(f"add: {addition} \nsubtract: {subtraction} \nmultiply: {multiplication} \ndivide: {division}")

add: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 
subtract: [[0 0 0]
 [0 0 0]
 [0 0 0]] 
multiply: [[ 1  4  9]
 [16 25 36]
 [49 64 81]] 
divide: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#  2

In [70]:
a = np.array ([1,2,3,4,5])
sum_exp = np.sum (np.exp(a))
log = np.log(sum_exp)
sum_exp_base2 = np.sum(np.exp2(a))
print(log)
print(sum_exp_base2)

5.451914395937593
62.0


#  3

In [71]:
a = np.arange(10)
print(np.true_divide(a,3))


[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


#  4

In [72]:
a = np.arange(6)
num = 2.5
print (np.floor_divide(a, num))

[0. 0. 0. 1. 1. 2.]


#  5

In [73]:
a = np.arange(10)
num = 3
print(np.power(a, num))

[  0   1   8  27  64 125 216 343 512 729]


#  6

In [74]:
a = np.arange(10)
num = 3
print(np.remainder(a, num))

[0 1 2 0 1 2 0 1 2 0]


# 7

In [75]:
a = np.arange(-5, 6)
print(a)
print(np.abs(a))

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[5 4 3 2 1 0 1 2 3 4 5]


# 8

In [76]:
a = np.random.rand(5)
decimalplaces = 3
print(a)
print(np.round(a, decimalplaces))

[0.04197633 0.1790773  0.7763082  0.38237519 0.90191779]
[0.042 0.179 0.776 0.382 0.902]


# 9

In [77]:
a = np.random.rand(5) * 10
print(a)
print(np.round(a, 0))

[6.74540208 5.62173493 7.71646106 3.05521479 8.45488253]
[7. 6. 8. 3. 8.]


# 10

In [78]:
a = np.random.rand(5) * 10 
print(a)
print(np.ceil(a))
print(np.floor(a))
print(np.trunc(a))

[2.55856928 1.03871501 3.03550548 6.75907805 6.66940866]
[3. 2. 4. 7. 7.]
[2. 1. 3. 6. 6.]
[2. 1. 3. 6. 6.]


# 11

In [79]:
a = np.trunc(np.random.random((5,3))*10)
b = np.trunc(np.random.random((3,2))*10)
c = np.dot(a,b)
print(a)
print(b) 
print("result:")
print(c)

[[9. 4. 0.]
 [2. 1. 9.]
 [1. 5. 7.]
 [1. 3. 6.]
 [3. 5. 5.]]
[[4. 6.]
 [6. 2.]
 [8. 8.]]
result:
[[60. 62.]
 [86. 86.]
 [90. 72.]
 [70. 60.]
 [82. 68.]]


# 12

In [80]:
a = np.array([1 + 2j, 3 + 4j, 5 + 6j, 7 + 8j])
b = np.array([9 + 10j, 11 + 12j, 13 + 14j, 15 + 16j])
c = np.dot(a,b)
d = a@b

print(c)
print(d)

(-68+488j)
(-68+488j)


# 13

In [81]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print( np.inner(a, b))

32


# 14

In [82]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])  

inner_product = np.inner(a, b)
outer_product = np.outer(a, b)
cross_product = np.cross(a, b)

print(inner_product )
print(outer_product )
print(cross_product )



32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]


# 15

# 16

In [83]:
a = np.array([1, -4, 7])
print(f"roots of first polynomial: {np.roots(a)}") # answer on website is wrong
b = np.array ([1,-11,9,-10])
print(f"roots of second polynomial: {np.roots(b)}") # answer on website is wrong


roots of first polynomial: [2.+1.73205081j 2.-1.73205081j]
roots of second polynomial: [10.21476143+0.j          0.39261928+0.90819903j  0.39261928-0.90819903j]


# 17

In [84]:
sample_coeff = [1,2,3] # 1*x^2 +2x^1+3x^0
for i in range (4):
    print(f"when x={i} y = {np.polyval(sample_coeff, i)}")


when x=0 y = 3
when x=1 y = 6
when x=2 y = 11
when x=3 y = 18


# 18

In [85]:
a = [1,2,3] # 1*x^2 +2x^1+3x^0
b = [2,1,0] # 2*x^2 +1x^1+0x^0

print(np.polyadd(a,b))
print(np.polysub(a,b))
print(np.polymul(a,b))
print(np.polydiv(a,b))

[3 3 3]
[-1  1  3]
[2 5 8 3 0]
(array([0.5]), array([1.5, 3. ]))


# 19

In [86]:
a = np.array([[10, 30], [20, 60]])
print(f'mean across columns: {np.mean(a, axis=0)}')
print(f'mean across rows: {np.mean(a, axis=1)}')

mean across columns: [15. 45.]
mean across rows: [20. 40.]


# 20

In [87]:
random_array = np.random.rand(1000)

print(f"Average (mean) of the array: {np.mean(random_array)}")
print(f"Variance of the array: {np.var(random_array)}")
print(f"Standard Deviation of the array: {np.std(random_array)}")

Average (mean) of the array: 0.5103502548876443
Variance of the array: 0.0795845937110131
Standard Deviation of the array: 0.28210741520033306


# 21

In [88]:
angles = []
for i in range (0, 361, 45):
    angles.append(i)
print(angles)
radians = np.array(angles) * np.pi / 180
print (f"sin of a given array \n{np.sin(radians)}")
print (f"cos of a given array \n{np.cos(radians)}")
print (f"tan of a given array \n{np.tan(radians)}")

[0, 45, 90, 135, 180, 225, 270, 315, 360]
sin of a given array 
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]
cos of a given array 
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01
  1.00000000e+00]
tan of a given array 
[ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16  1.00000000e+00  5.44374645e+15 -1.00000000e+00
 -2.44929360e-16]


# 22

In [89]:
values = np.arange(-1, 1.1, 0.5)
    
print (f"inverse sin of a given array \n{np.arcsin(values)/np.pi*180}\n")
print (f"inverse cos of a given array \n{np.arccos(values)/np.pi*180}\n")
print (f"inverse tan of a given array \n{np.arctan(values)/np.pi*180}")


inverse sin of a given array 
[-90. -30.   0.  30.  90.]

inverse cos of a given array 
[180. 120.  90.  60.   0.]

inverse tan of a given array 
[-45.         -26.56505118   0.          26.56505118  45.        ]


# 23

In [90]:
radians = np.array ([-np.pi, -np.pi/2, np.pi/2, np.pi])
degrees = np.degrees(radians)
print(f"radians: {radians}")
print(f"degrees: {degrees}")


radians: [-3.14159265 -1.57079633  1.57079633  3.14159265]
degrees: [-180.  -90.   90.  180.]


# 24

In [91]:
degrees = np.array([-180., -90., 90., 180.])
radians = np.radians(degrees)

print(f"degrees: {degrees}")
print(f"radians: {radians}")

degrees: [-180.  -90.   90.  180.]
radians: [-3.14159265 -1.57079633  1.57079633  3.14159265]


# 25

In [92]:
a = np.array ([-1., 0, 1.])
print (f"hyperbolic sin of a given array \n{np.sinh(a)}\n")
print (f"hyperbolic cos of a given array \n{np.cosh(a)}\n")
print (f"hyperbolic tan of a given array \n{np.tanh(a)}")


hyperbolic sin of a given array 
[-1.17520119  0.          1.17520119]

hyperbolic cos of a given array 
[1.54308063 1.         1.54308063]

hyperbolic tan of a given array 
[-0.76159416  0.          0.76159416]


# 26

In [93]:
a = np.array ([3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])

decimals = 0

print (f"around: {np.around(a, decimals=decimals)}")
print (f"floor: {np.floor(a)}")
print (f"ceil: {np.ceil(a)}")
print (f"truncate: {np.trunc(a)}")
print (f"round: {[round(item) for item in a]}")


around: [ 3.  4.  4.  3. -3. -4. -6.]
floor: [ 3.  3.  4.  2. -4. -4. -6.]
ceil: [ 4.  4.  5.  3. -3. -3. -5.]
truncate: [ 3.  3.  4.  2. -3. -3. -5.]
round: [3, 4, 4, 3, -3, -4, -6]


# 27

In [94]:
a= np.array([[1, 2, 3],
             [4, 5, 6]])
cumulSum = np.cumsum(a)
rowssum = np.sum(a, axis=0)
colsum = np.sum(a, axis=1)

print(f"cumulative sum: {cumulSum}")
print(f"sum over rows: {rowssum}")
print(f"sum over columns: {colsum}")

cumulative sum: [ 1  3  6 10 15 21]
sum over rows: [5 7 9]
sum over columns: [ 6 15]


# 28

In [95]:
a= np.array([[1, 2, 3],
             [4, 5, 6]])
cumulSum = np.cumprod(a)
rowssum = np.prod(a, axis=0)
colsum = np.prod(a, axis=1)

print(f"cumulative product: {cumulSum}")
print(f"product over rows: {rowssum}")
print(f"product over columns: {colsum}")

cumulative product: [  1   2   6  24 120 720]
product over rows: [ 4 10 18]
product over columns: [  6 120]


# 29

In [96]:
a = np.array([1, 3, 5, 7, 0])
print(np.diff(a))

[ 2  2  2 -7]


# 30

In [97]:
a = np.array([1, 3, 5, 7, 0])
diff = np.diff(a)
print(np.concatenate(([0, 0], diff, [200])))



[  0   0   2   2   2  -7 200]


# 31

In [98]:
a = np.array ([[1, 2, 3, 4]])
print(np.exp(a))

[[ 2.71828183  7.3890561  20.08553692 54.59815003]]


# 32

In [99]:
a = np.array ([[1, 2, 3, 4]])
print(np.exp(a)-1)

[[ 1.71828183  6.3890561  19.08553692 53.59815003]]


# 33

In [100]:
a = np.array ([[1, 2, 3, 4]])
print(np.pow(2, a))

[[ 2  4  8 16]]


# 34

In [101]:
a = np.array([1, 2.71828183, 7.3890561 ])
print(f"natural log: {np.log(a)}")
print(f"log b10: {np.log10(a)}")
print(f"log b2: {np.log2(a)}")

natural log: [0. 1. 2.]
log b10: [0.         0.43429448 0.86858896]
log b2: [0.         1.44269504 2.88539008]


# 35

In [102]:
a = np.array ([[1.e-099, 1.e-100]])
#print(np.log(a+1))
print(np.log1p(a))

[[1.e-099 1.e-100]]


# 36

In [103]:
a = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4]) 
print(np.signbit(a))

[ True  True  True  True False False False False False]


# 37

In [104]:
a = np.array([-1, 0, 1, 2])
testsign = -1.0
testsign2 = +1.0

print(f"negative: {np.copysign(a, testsign)}")

print(f"positive: {np.copysign(a, testsign2)}")

negative: [-1. -0. -1. -2.]
positive: [1. 0. 1. 2.]


# 38

In [105]:
a = np.array ([0, 1, -1])
print(f"original: {a}")
print(np.negative(a))
print(-a)

original: [ 0  1 -1]
[ 0 -1  1]
[ 0 -1  1]


# 39

In [106]:
a = np.array ([1., 2., 0.2, 0.3])
print(np.reciprocal(a))
print(1/a)

[1.         0.5        5.         3.33333333]
[1.         0.5        5.         3.33333333]


# 40

In [107]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[1,2]])

print(np.power(x, y))

[[ 1  4]
 [ 3 16]]


# 41

In [108]:
a = np.array([1, 3, 5, 0, -1, -7, 0, 5])

print(np.sign(a))

a1 = np.where((a > 0), 
              1, 
              np.where((a < 0), 
                       -1, 
                       a))
print(a1)

[ 1  1  1  0 -1 -1  0  1]
[ 1  1  1  0 -1 -1  0  1]
