In [50]:
import numpy as np

# 1

In [51]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2

In [52]:
a2 = np.arange(10,50)
print(a2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3

In [53]:
print(a2[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 4

In [54]:
a = np.arange(9).reshape((3,3))
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 5

In [55]:
a = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(a))

(array([0, 1, 4]),)


# 6

In [56]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 7 

In [57]:
a = np.random.rand(9).reshape((3,3))
print(a)
print(f"max value is: {np.max(a)}")
print(f"min value is: {np.min(a)}")

[[0.24911737 0.33547054 0.76268613]
 [0.91330704 0.89517667 0.88750345]
 [0.02696736 0.4433433  0.4884774 ]]
max value is: 0.9133070392486424
min value is: 0.026967359935591295


# 8

In [58]:
a = np.random.rand(5,5)
print(a)

[[0.40217622 0.77662275 0.22296632 0.55568085 0.95801871]
 [0.57937852 0.04627306 0.20623269 0.23474445 0.54499688]
 [0.86132806 0.09491071 0.73904575 0.2514704  0.89133829]
 [0.62644427 0.86870394 0.41251667 0.14623778 0.81308168]
 [0.62709679 0.99778205 0.20407974 0.62179607 0.18101089]]


# 9

In [59]:
array = np.array([1, 3, 5, 11, 15, 20, 25])
target = 14
index_closest = np.abs(array - target).argmin()

print(array[index_closest])

15


# 10

In [60]:
array = np.array([[5, 9, 3], [10, 2, 15], [6, 7, 8]])

index_max = array.argmax()
row, col = np.unravel_index(index_max, array.shape)

array[row][col] = 0

print(array)



[[ 5  9  3]
 [10  2  0]
 [ 6  7  8]]


# 11

In [61]:
array = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])

num, counts = np.unique(array, return_counts=True)
MostCommon =num[np.argmax(counts)]

print(f"most common value is: {MostCommon}")


most common value is: 5


# 12

In [62]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrayT = np.transpose(array)
print (array @ arrayT)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


# 13

In [63]:
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print (np.linalg.det(matrix))


-306.0


# 14

In [64]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det = np.linalg.det(matrix)

if det != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print(f"inverse is: {inverse_matrix}")
else:
    print("inverse does not exist, matrix is singular")


inverse is: [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
